/**
 * Server-side proxy for the Gemini AI API.
 *
 * This route keeps the Gemini API key out of the browser by forwarding
 * route-generation requests from the frontend to Google Generative Language
 * API entirely server-side. The key is read from `GEMINI_API_KEY` — a
 * server-only environment variable (no NEXT_PUBLIC_ prefix).
 *
 * Request body  (JSON):
 *   systemPrompt  string  – Full system context
 *   userPrompt    string  – User's generation request
 *   model?        string  – Gemini model name (default: gemini-2.5-flash)
 *   temperature?  number  – Sampling temperature (default: 0.7)
 *   maxTokens?    number  – Max output tokens (default: 8192)
 *
 * Success response (200):
 *   { text: string; tokensUsed?: number }
 *
 * Error response (4xx / 5xx):
 *   { error: string }
 */

import { NextRequest, NextResponse } from 'next/server';

const GEMINI_API_BASE = 'https://generativelanguage.googleapis.com/v1beta/models';
const DEFAULT_MODEL = 'gemini-2.5-flash';

interface GenerateRouteRequest {
  systemPrompt: string;
  userPrompt: string;
  model?: string;
  temperature?: number;
  maxTokens?: number;
}

export async function POST(request: NextRequest): Promise<NextResponse> {
  // --- Validate API key availability (server-side only) ---
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey || apiKey.trim() === '') {
    return NextResponse.json(
      { error: 'Gemini API key is not configured on the server. Set GEMINI_API_KEY in the server environment.' },
      { status: 503 }
    );
  }

  // --- Parse request body ---
  let body: GenerateRouteRequest;
  try {
    body = await request.json();
  } catch {
    return NextResponse.json({ error: 'Invalid JSON in request body.' }, { status: 400 });
  }

  const { systemPrompt, userPrompt, model, temperature, maxTokens } = body;

  if (!systemPrompt || !userPrompt) {
    return NextResponse.json(
      { error: 'Both systemPrompt and userPrompt are required.' },
      { status: 400 }
    );
  }

  const resolvedModel = model ?? DEFAULT_MODEL;
  const resolvedTemperature = temperature ?? 0.7;
  const resolvedMaxTokens = maxTokens ?? 8192;

  // --- Forward request to Gemini API ---
  const geminiUrl = `${GEMINI_API_BASE}/${resolvedModel}:generateContent?key=${apiKey}`;

  let geminiResponse: Response;
  try {
    geminiResponse = await fetch(geminiUrl, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        contents: [
          {
            parts: [
              { text: systemPrompt },
              { text: `\n\nUSER REQUEST: ${userPrompt}` },
            ],
          },
        ],
        generationConfig: {
          temperature: resolvedTemperature,
          maxOutputTokens: resolvedMaxTokens,
          topP: 0.95,
          topK: 64,
        },
        safetySettings: [
          { category: 'HARM_CATEGORY_HARASSMENT', threshold: 'BLOCK_ONLY_HIGH' },
          { category: 'HARM_CATEGORY_HATE_SPEECH', threshold: 'BLOCK_ONLY_HIGH' },
          { category: 'HARM_CATEGORY_SEXUALLY_EXPLICIT', threshold: 'BLOCK_ONLY_HIGH' },
          { category: 'HARM_CATEGORY_DANGEROUS_CONTENT', threshold: 'BLOCK_ONLY_HIGH' },
        ],
      }),
    });
  } catch (networkError) {
    console.error('[/api/ai/generate-route] Network error calling Gemini:', networkError);
    return NextResponse.json(
      { error: 'Failed to reach Gemini API. Check server network connectivity.' },
      { status: 502 }
    );
  }

  // --- Handle non-OK responses from Gemini ---
  if (!geminiResponse.ok) {
    let errorMessage = geminiResponse.statusText;
    try {
      const errorData = await geminiResponse.json();
      errorMessage = errorData?.error?.message ?? errorMessage;
    } catch { /* ignore parse error */ }

    console.error(`[/api/ai/generate-route] Gemini API error ${geminiResponse.status}: ${errorMessage}`);
    return NextResponse.json(
      { error: `Gemini API error: ${errorMessage}` },
      { status: geminiResponse.status }
    );
  }

  // --- Parse and forward successful response ---
  let geminiData: Record<string, unknown>;
  try {
    geminiData = await geminiResponse.json();
  } catch {
    return NextResponse.json({ error: 'Failed to parse Gemini API response.' }, { status: 502 });
  }

  const generatedText =
    (geminiData.candidates as Array<{ content: { parts: Array<{ text: string }> } }> | undefined)
      ?.[0]?.content?.parts?.[0]?.text;

  if (!generatedText) {
    return NextResponse.json(
      { error: 'No content generated by Gemini. The model may have blocked the request.' },
      { status: 422 }
    );
  }

  const tokensUsed =
    (geminiData.usageMetadata as { totalTokenCount?: number } | undefined)?.totalTokenCount;

  return NextResponse.json({ text: generatedText, tokensUsed });
}
