-- Tier 3 demo data, dev profile only. Six completed transactions (one cash + one online per demo
-- route's "today" trip — see core-service's V907__demo_trips.sql), fare amounts matching the
-- base_fare bands seeded in V900 for each route's distance/class: Colombo-Kandy (115 km,
-- semi-luxury, section 5) = 120.00, Colombo-Galle (119 km, luxury, section 5) = 145.00,
-- Colombo-Negombo (37 km, normal, section 2) = 35.00.
--
-- Neither Transactions.paymentMethod nor Transactions.status has @Enumerated(EnumType.STRING) in
-- the entity, so Hibernate persists both as ordinals matching declaration order — confirmed
-- against the base_fare/transactions CHECK constraints in V001__baseline.sql
-- (payment_method 0-1, status 0-4): Method {CASH=0, ONLINE=1}, Status
-- {PENDING=0, COMPLETED=1, FAILED=2, ISSUED=3, REFUNDED=4}. Every demo transaction below is a
-- finished, successful sale, hence status=1 (COMPLETED) throughout.
--
-- Idempotent via ON CONFLICT (transaction_id)/(payment_id) DO NOTHING (per the plan's Tier 3
-- guidance) — safe to re-run. transaction_id/payment_id are GENERATED BY DEFAULT AS IDENTITY
-- (not ALWAYS), so explicit values are allowed without an OVERRIDING clause.
INSERT INTO transactions (transaction_id, payment_method, total_amount, status)
VALUES
    (1, 0, 120.00, 1), -- cash, Colombo-Kandy
    (2, 1, 120.00, 1), -- online, Colombo-Kandy
    (3, 0, 145.00, 1), -- cash, Colombo-Galle
    (4, 1, 145.00, 1), -- online, Colombo-Galle
    (5, 0, 35.00, 1),  -- cash, Colombo-Negombo
    (6, 1, 35.00, 1)   -- online, Colombo-Negombo
ON CONFLICT (transaction_id) DO NOTHING;

-- conductor_id is the text form of that route's demo conductor UUID (user-service,
-- docs/dev-seed-contract.md) — Cash has no FK to user-service, same loose-coupling pattern as
-- Tickets.
INSERT INTO cash_payments (payment_id, conductor_id, action, transaction_id)
VALUES
    (1, '00000000-0000-0000-0000-000000000301', 'ISSUED', 1), -- Saman Kumara, Colombo-Kandy
    (2, '00000000-0000-0000-0000-000000000302', 'ISSUED', 3), -- Nirosha Fernando, Colombo-Galle
    (3, '00000000-0000-0000-0000-000000000303', 'ISSUED', 5)  -- Ranjith Silva, Colombo-Negombo
ON CONFLICT (payment_id) DO NOTHING;

-- passenger_id is the text form of that route's demo passenger UUID (user-service,
-- docs/dev-seed-contract.md).
INSERT INTO online (payment_id, passenger_id, amount, method, status, transaction_ref, transaction_id)
VALUES
    (1, '00000000-0000-0000-0000-000000000201', 120.00, 'PAYHERE', 'SUCCESS',
     'PAYHERE-REF-000101', 2), -- Dilani Perera, Colombo-Kandy
    (2, '00000000-0000-0000-0000-000000000202', 145.00, 'PAYHERE', 'SUCCESS',
     'PAYHERE-REF-000102', 4), -- Kasun Mendis, Colombo-Galle
    (3, '00000000-0000-0000-0000-000000000203', 35.00, 'PAYHERE', 'SUCCESS',
     'PAYHERE-REF-000103', 6)  -- Ishara Gunawardena, Colombo-Negombo
ON CONFLICT (payment_id) DO NOTHING;
