-- Tier 3 demo data, dev profile only. Six tickets — one cash (anonymous walk-up passenger,
-- validated at boarding) and one online (booked ahead by a named demo passenger, not yet
-- boarded) per route — against each route's "today" trip from core-service's
-- V907__demo_trips.sql. bus_id/trip_id/conductor_id/passenger_id are plain string columns (no
-- FK to core-service or user-service — see Tickets' entity comment), holding the real UUIDs from
-- docs/dev-seed-contract.md as text so the data is traceable across services without a hard
-- coupling. start/end location ids are the route's start/end core-service Stop UUIDs, also as
-- text.
--
-- Idempotent via ON CONFLICT (ticket_id) DO NOTHING (per the plan's Tier 3 guidance) — safe to
-- re-run. ticket_id is GENERATED BY DEFAULT AS IDENTITY (not ALWAYS), so explicit values are
-- allowed without an OVERRIDING clause.
INSERT INTO tickets (ticket_id, bus_id, trip_id, conductor_id, passenger_id, seat_number,
                      start_location_id, end_location_id, fare_amount, issue_method, status,
                      transactions_transaction_id)
VALUES
    -- Colombo-Kandy, today's trip (bus WP CAB-7734, conductor Saman Kumara)
    (1, '00000000-0000-0000-0000-000000010302', '00000000-0000-0000-0000-000000010407',
     '00000000-0000-0000-0000-000000000301', NULL, '12A',
     '00000000-0000-0000-0000-000000010201', '00000000-0000-0000-0000-000000010204',
     120.00, 'CONDUCTOR', 'VALID', 1),
    (2, '00000000-0000-0000-0000-000000010302', '00000000-0000-0000-0000-000000010407',
     '00000000-0000-0000-0000-000000000301', '00000000-0000-0000-0000-000000000201', '14B',
     '00000000-0000-0000-0000-000000010201', '00000000-0000-0000-0000-000000010204',
     120.00, 'ONLINE', 'NOT_VALID', 2),

    -- Colombo-Galle expressway, today's trip (bus SP CAB-9981, conductor Nirosha Fernando)
    (3, '00000000-0000-0000-0000-000000010304', '00000000-0000-0000-0000-000000010408',
     '00000000-0000-0000-0000-000000000302', NULL, '5A',
     '00000000-0000-0000-0000-000000010201', '00000000-0000-0000-0000-000000010207',
     145.00, 'CONDUCTOR', 'VALID', 3),
    (4, '00000000-0000-0000-0000-000000010304', '00000000-0000-0000-0000-000000010408',
     '00000000-0000-0000-0000-000000000302', '00000000-0000-0000-0000-000000000202', '7C',
     '00000000-0000-0000-0000-000000010201', '00000000-0000-0000-0000-000000010207',
     145.00, 'ONLINE', 'NOT_VALID', 4),

    -- Colombo-Negombo, today's trip (bus CP NA-1187, conductor Ranjith Silva)
    (5, '00000000-0000-0000-0000-000000010306', '00000000-0000-0000-0000-000000010409',
     '00000000-0000-0000-0000-000000000303', NULL, '3A',
     '00000000-0000-0000-0000-000000010201', '00000000-0000-0000-0000-000000010209',
     35.00, 'CONDUCTOR', 'VALID', 5),
    (6, '00000000-0000-0000-0000-000000010306', '00000000-0000-0000-0000-000000010409',
     '00000000-0000-0000-0000-000000000303', '00000000-0000-0000-0000-000000000203', '8B',
     '00000000-0000-0000-0000-000000010201', '00000000-0000-0000-0000-000000010209',
     35.00, 'ONLINE', 'NOT_VALID', 6)
ON CONFLICT (ticket_id) DO NOTHING;
