import { Router } from 'express';
import { env } from '../config/env';

/**
 * Server-side proxy for the Gemini AI API.
 *
 * Keeps the Gemini API key out of the browser by forwarding route-generation
 * requests from the frontend to Google's Generative Language API entirely
 * server-side. Mounted behind authMiddleware (see app.ts) — requires a valid
 * portal session, unlike the Next.js route this replaces which had no
 * server-side auth check of its own.
 *
 * Request body  (JSON):
 *   systemPrompt  string  – Full system context
 *   userPrompt    string  – User's generation request
 *   model?        string  – Gemini model name (default: gemini-2.5-flash)
 *   temperature?  number  – Sampling temperature (default: 0.7)
 *   maxTokens?    number  – Max output tokens (default: 8192)
 *
 * Success response (200): { text: string; tokensUsed?: number }
 * Error response (4xx / 5xx): { error: string }
 */

const GEMINI_API_BASE = 'https://generativelanguage.googleapis.com/v1beta/models';
const DEFAULT_MODEL = 'gemini-2.5-flash';

interface GenerateRouteRequest {
  systemPrompt?: string;
  userPrompt?: string;
  model?: string;
  temperature?: number;
  maxTokens?: number;
}

interface GeminiCandidate {
  content: { parts: Array<{ text: string }> };
}

export const aiRouter = Router();

aiRouter.post('/generate-route', async (req, res) => {
  const apiKey = env.GEMINI_API_KEY;
  if (!apiKey || apiKey.trim() === '') {
    res.status(503).json({
      error: 'Gemini API key is not configured on the server. Set GEMINI_API_KEY in the server environment.',
    });
    return;
  }

  const { systemPrompt, userPrompt, model, temperature, maxTokens } = req.body as GenerateRouteRequest;

  if (!systemPrompt || !userPrompt) {
    res.status(400).json({ error: 'Both systemPrompt and userPrompt are required.' });
    return;
  }

  const resolvedModel = model ?? DEFAULT_MODEL;
  const resolvedTemperature = temperature ?? 0.7;
  const resolvedMaxTokens = maxTokens ?? 8192;

  const geminiUrl = `${GEMINI_API_BASE}/${resolvedModel}:generateContent?key=${apiKey}`;

  let geminiResponse: Response;
  try {
    geminiResponse = await fetch(geminiUrl, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        contents: [
          {
            parts: [{ text: systemPrompt }, { text: `\n\nUSER REQUEST: ${userPrompt}` }],
          },
        ],
        generationConfig: {
          temperature: resolvedTemperature,
          maxOutputTokens: resolvedMaxTokens,
          topP: 0.95,
          topK: 64,
        },
        safetySettings: [
          { category: 'HARM_CATEGORY_HARASSMENT', threshold: 'BLOCK_ONLY_HIGH' },
          { category: 'HARM_CATEGORY_HATE_SPEECH', threshold: 'BLOCK_ONLY_HIGH' },
          { category: 'HARM_CATEGORY_SEXUALLY_EXPLICIT', threshold: 'BLOCK_ONLY_HIGH' },
          { category: 'HARM_CATEGORY_DANGEROUS_CONTENT', threshold: 'BLOCK_ONLY_HIGH' },
        ],
      }),
    });
  } catch (networkError) {
    console.error('[/api/ai/generate-route] Network error calling Gemini:', networkError);
    res.status(502).json({ error: 'Failed to reach Gemini API. Check server network connectivity.' });
    return;
  }

  if (!geminiResponse.ok) {
    let errorMessage = geminiResponse.statusText;
    try {
      const errorData = (await geminiResponse.json()) as { error?: { message?: string } };
      errorMessage = errorData?.error?.message ?? errorMessage;
    } catch {
      // ignore parse error, fall back to statusText
    }

    console.error(`[/api/ai/generate-route] Gemini API error ${geminiResponse.status}: ${errorMessage}`);
    res.status(geminiResponse.status).json({ error: `Gemini API error: ${errorMessage}` });
    return;
  }

  let geminiData: Record<string, unknown>;
  try {
    geminiData = (await geminiResponse.json()) as Record<string, unknown>;
  } catch {
    res.status(502).json({ error: 'Failed to parse Gemini API response.' });
    return;
  }

  const generatedText = (geminiData.candidates as GeminiCandidate[] | undefined)?.[0]?.content?.parts?.[0]?.text;

  if (!generatedText) {
    res.status(422).json({ error: 'No content generated by Gemini. The model may have blocked the request.' });
    return;
  }

  const tokensUsed = (geminiData.usageMetadata as { totalTokenCount?: number } | undefined)?.totalTokenCount;

  res.json({ text: generatedText, tokensUsed });
});
