-- V001__baseline.sql — captures the schema as built by Hibernate ddl-auto=update against
-- current entities as of the migration/seed-data standardization plan's Phase 1
-- (docs/plans/Database-Migrations-and-Seed-Data-Plan.md), generated via:
--   pg_dump --schema-only --no-owner --no-privileges --no-comments -d busmate_ticketing
-- then trimmed of pg_dump's psql-only meta-commands and session-level SET statements
-- so it is plain, portable Postgres SQL. Flyway adopts this as version 1 via
-- baseline-on-migrate/baseline-version (see application.yml). Do not hand-edit; any
-- further schema change is a new V00x migration, never an edit to this file.

--
-- Name: base_fare; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.base_fare (
    section integer NOT NULL,
    expressway_super_luxury_fare double precision,
    luxury_fare double precision,
    normal_fare double precision NOT NULL,
    semi_luxury_fare double precision,
    super_luxury_fare double precision
);


--
-- Name: cash_payments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cash_payments (
    payment_id bigint NOT NULL,
    action character varying(255) NOT NULL,
    conductor_id character varying(255) NOT NULL,
    transaction_id integer,
    CONSTRAINT cash_payments_action_check CHECK (((action)::text = ANY ((ARRAY['ISSUED'::character varying, 'CANCELLED'::character varying])::text[])))
);


--
-- Name: cash_payments_payment_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.cash_payments ALTER COLUMN payment_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cash_payments_payment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: online; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.online (
    payment_id bigint NOT NULL,
    amount numeric(10,2) NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    method character varying(255) NOT NULL,
    passenger_id character varying(255),
    status character varying(255) NOT NULL,
    transaction_ref character varying(100),
    updated_at timestamp(6) without time zone,
    transaction_id integer,
    CONSTRAINT online_method_check CHECK (((method)::text = ANY ((ARRAY['PAYHERE'::character varying, 'CASH'::character varying, 'CARD'::character varying])::text[]))),
    CONSTRAINT online_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'SUCCESS'::character varying, 'FAILED'::character varying, 'REFUNDED'::character varying])::text[])))
);


--
-- Name: online_payment_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.online ALTER COLUMN payment_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.online_payment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: route_fare_section; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.route_fare_section (
    id uuid NOT NULL,
    distance_from_start double precision NOT NULL,
    route_id character varying(255) NOT NULL,
    section_id integer NOT NULL,
    section_name character varying(255) NOT NULL
);


--
-- Name: tickets; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tickets (
    ticket_id bigint NOT NULL,
    end_location_id character varying(255),
    start_location_id character varying(255),
    bus_id character varying(255) NOT NULL,
    conductor_id character varying(255),
    fare_amount numeric(10,2) NOT NULL,
    issue_method character varying(255) NOT NULL,
    issued_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    passenger_id character varying(255),
    seat_number character varying(10),
    status character varying(255) NOT NULL,
    trip_id character varying(255) NOT NULL,
    transactions_transaction_id integer,
    CONSTRAINT tickets_issue_method_check CHECK (((issue_method)::text = ANY ((ARRAY['CONDUCTOR'::character varying, 'ONLINE'::character varying])::text[]))),
    CONSTRAINT tickets_status_check CHECK (((status)::text = ANY ((ARRAY['VALID'::character varying, 'NOT_VALID'::character varying, 'CANCELLED'::character varying])::text[])))
);


--
-- Name: tickets_ticket_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tickets ALTER COLUMN ticket_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tickets_ticket_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: transactions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.transactions (
    transaction_id integer NOT NULL,
    total_amount double precision,
    created_at timestamp(6) without time zone,
    payment_method smallint,
    status smallint,
    updated_at timestamp(6) without time zone,
    CONSTRAINT transactions_payment_method_check CHECK (((payment_method >= 0) AND (payment_method <= 1))),
    CONSTRAINT transactions_status_check CHECK (((status >= 0) AND (status <= 4)))
);


--
-- Name: transactions_transaction_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.transactions ALTER COLUMN transaction_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.transactions_transaction_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: base_fare base_fare_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.base_fare
    ADD CONSTRAINT base_fare_pkey PRIMARY KEY (section);


--
-- Name: cash_payments cash_payments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cash_payments
    ADD CONSTRAINT cash_payments_pkey PRIMARY KEY (payment_id);


--
-- Name: online online_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.online
    ADD CONSTRAINT online_pkey PRIMARY KEY (payment_id);


--
-- Name: route_fare_section route_fare_section_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.route_fare_section
    ADD CONSTRAINT route_fare_section_pkey PRIMARY KEY (id);


--
-- Name: tickets tickets_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tickets
    ADD CONSTRAINT tickets_pkey PRIMARY KEY (ticket_id);


--
-- Name: transactions transactions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT transactions_pkey PRIMARY KEY (transaction_id);


--
-- Name: cash_payments uk2vbddki02bvqrbo5jme4y7qgj; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cash_payments
    ADD CONSTRAINT uk2vbddki02bvqrbo5jme4y7qgj UNIQUE (transaction_id);


--
-- Name: online uklb9rg86s0fgxje7r0rt8xjpr9; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.online
    ADD CONSTRAINT uklb9rg86s0fgxje7r0rt8xjpr9 UNIQUE (transaction_id);


--
-- Name: online fk8dkp93o9kcdwi1pgdu9viy315; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.online
    ADD CONSTRAINT fk8dkp93o9kcdwi1pgdu9viy315 FOREIGN KEY (transaction_id) REFERENCES public.transactions(transaction_id);


--
-- Name: cash_payments fkk19s29lmq2ds15e36rn32n5x1; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cash_payments
    ADD CONSTRAINT fkk19s29lmq2ds15e36rn32n5x1 FOREIGN KEY (transaction_id) REFERENCES public.transactions(transaction_id);


--
-- Name: tickets fkrgpagb1bdkd5jesqchkue8urr; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tickets
    ADD CONSTRAINT fkrgpagb1bdkd5jesqchkue8urr FOREIGN KEY (transactions_transaction_id) REFERENCES public.transactions(transaction_id);


