name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Spring Boot App
        run: |
          ./mvnw clean package -DskipTests

      - name: Copy files to EC2
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE || '' }}
          source: "Dockerfile,target/*.jar"
          target: "~/app-${{ github.repository_owner }}-${{ github.event.repository.name }}"

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE || '' }}
          script: |
            cd ~/app-${{ github.repository_owner }}-${{ github.event.repository.name }}
            docker stop ${GITHUB_REPOSITORY##*/} || true
            docker rm ${GITHUB_REPOSITORY##*/} || true
            docker build -t ${GITHUB_REPOSITORY##*/}-image .
            docker run -d --network=host --name ${GITHUB_REPOSITORY##*/} -p 8081:8080 ${GITHUB_REPOSITORY##*/}-image
